### ISSUE TITLE
Java | Webhooks - Cannot make Subscription to Channel

### ISSUE THREAD

**Issue by tarasklimenko** [attdevsupport/att-html5-sdk#114]
#### Description: 
Cannot make Subscription to Notification Channel, messages are downloaded successfully after consent is given but left with following loading icon: 

![image](https://cloud.githubusercontent.com/assets/4699745/6452627/da8297e6-c0eb-11e4-9df7-7fd7f919fea1.png)

and error: 
```
Uncaught TypeError: Cannot read property 'createNotificationSubscription' of undefined
```
#### Actual:
subscription to channel is not made successfully

#### Expected:
createNotificationSubscription method to work properly and subscribe to channel

**Comment by mattcobb** [comment]
I'm not able to repro this.  What do you have for scope in the config file?

**Comment by tarasklimenko** [comment]
I was thinking it might be the scope, so I was changing it around but initially it was like so: 
```
clientModelScope : ADS,MMS,SMS,SPEECH,STTC,TTS
```
and I tried adding NOTIFICATIONCHANNEL scope but I'm yielding same results

**Comment by mattcobb** [comment]
Did you rebuild the java after?

**Comment by tarasklimenko** [comment]
Ok so looks like after I did that I was able to go through the consent flow properly, though I was getting an error where I was unable to create message index: 
![image](https://cloud.githubusercontent.com/assets/4699745/6468804/8c690dfa-c18c-11e4-8287-daa729e15d19.png)

After digging around I found that my pushnotifcationsurl in my dev portal app was not setup with proper url. 

Although, after that was successfully setup, I went through the consent flow successfully and now back at the same loading icon trying to make a subscription

**Comment by tarasklimenko** [comment]
Confirmed this is not an issue. Closing.
