### ISSUE TITLE
Java | Webhooks - Fails to list notifications

### ISSUE THREAD

**Issue by tarasklimenko** [attdevsupport/att-html5-sdk#115]
#### Description: 
When attempting to get list of notifications in HTML5 Java Sample App, no notifications are shown. 

requested:
```
GET http://localhost:4567/att/notification/v1/notifications
```
returned:
```
{}
```

#### Expected: 
When calling to get list of notifications, all notifications should be listed

#### Actual:
Notifications are not listed, "{}" empty response 

#### Repro:
1) Via HTML5 Java IAM Sample, Make channel & subscription
2) Make few sms/mms calls to make new notifications
3) Call to GET http://localhost:4567/att/notification/v1/notifications
4) Notice "{}" returned

**Comment by mattcobb** [comment]
The url in step 3 will give you the notifcations for the subscription on that java session.  If you want all notifications from all subscriptions, set enableUnsafeOperations=true and put /all on the end of the url.

**Comment by mattcobb** [comment]
Plus, if your using localhost:4567, the service can not reach that address. So sending sms/mms messages won't do anything.  You would have to simulate notifications using curl like i did in the demos.

**Comment by tarasklimenko** [comment]
Confirmed not bug, closing.
